# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_shape_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='shape_type',
            field=models.CharField(default='shape', max_length=20),
            preserve_default=False,
        ),
    ]
