# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shape_shape_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Line',
            new_name='Polyline',
        ),
        migrations.RenameField(
            model_name='shape',
            old_name='shape_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='id',
        ),
        migrations.AddField(
            model_name='shape',
            name='_leaflet_id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='encoded',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='options',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
