# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160506_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shape',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='shape',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 14, 50, 36, 848398, tzinfo=utc), verbose_name='last update'),
            preserve_default=False,
        ),
    ]
