# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160506_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='leafletJSON',
        ),
    ]
